version = 1

test_patterns = [
  "**/*_test.go"
]

[[analyzers]]
name = "go"
enabled = true

    [analyzers.meta]
    import_root = "github.com/purpleclay/nsv"

[[analyzers]]
name = "secrets"
enabled = true
