version: 2

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - dupl
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

linters-settings:
  dupl:
    threshold: 400
