builds:
  - skip: true

changelog:
  sort: desc
  use: github
  filters:
    exclude:
      - "^test"
      - "^chore"
      - "^ci"
  groups:
    - title: "Dependency Updates"
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 30
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 10
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 20
    - title: "Documentation Updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 40
    - title: "Other Work"
      order: 99

release:
  footer: |
    **Full Changelog**: https://github.com/purpleclay/gitz/compare/{{ .PreviousTag }}...{{ .Tag }}
    ## What to do next?
    - Follow me on [Twitter](https://twitter.com/purpleclaydev)
    - Follow me on [Fosstodon](https://fosstodon.org/@purpleclaydev)
