site_name: Gitz
site_description: Write fluent interactions to Git using the gitz library. Programmatically crafting git commands becomes a breeze!
copyright: Building tools to make developers' lives easier
repo_name: purpleclay/gitz
repo_url: https://github.com/purpleclay/gitz
# Only set during a release to ensure htmltest doesn't break due to non existent directories
site_url: ""
edit_uri: ""

theme:
  name: material
  custom_dir: docs/overrides
  logo: static/logo.png
  favicon: static/favicon.ico
  palette:
    primary: deep purple
    accent: purple
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started:
      - Git Checks: git/checks.md
      - Git Clone: git/clone.md
      - Git Config: git/config.md
      - Git Checkout: git/checkout.md
      - Git Pull: git/pull.md
      - Git Push: git/push.md
      - Git Stage: git/stage.md
      - Git Status: git/status.md
      - Git Commit: git/commit.md
      - Git Tag: git/tag.md
      - Git Log: git/log.md
      - Testing Framework:
          - Git Test: testing/git-test.md
      - Installation:
          - Package: install/package.md
      - Other Bits:
          - License: license.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/purpleclay
      name: Purple Clay on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/purpleclaydev
      name: Purple Clay on Twitter
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@purpleclaydev
      name: Purple Clay on Fosstodon
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/purpleclay
      name: Purple Clay on Docker Hub
    - icon: fontawesome/brands/golang
      link: https://pkg.go.dev/github.com/purpleclay/gitz
      name: Gitz GoDocs
  status:
    new: New Features Added
    deprecated: No Longer Supported

plugins:
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: true
      type: timeago
  - git-committers:
      enabled: !ENV [CI, false]
      repository: purpleclay/gitz
      branch: main
  - minify:
      enabled: !ENV [CI, false]
      minify_html: true
  - search
  - social
  - typeset

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - md_in_html
  - meta
  - toc:
      permalink: true
