name: CI Enhancement
description: Suggest a new CI enhancement
title: "[CI]: "
labels: [ci, enhancement, triage]
assignees:
  - purpleclay
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new CI enhancement request. Please be as descriptive and concise as possible. We value all input from the community.
  - type: textarea
    id: describe-enhancement
    attributes:
      label: Describe your enhancement
      description: A clear and concise description of the CI enhancement you are requesting.
      placeholder: Your enhancement?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/purpleclay/gitz/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
