name: ci
on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "*.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    paths:
      - "**/*.go"
      - "*.go"
      - "go.mod"
      - "go.sum"

permissions:
  contents: read

jobs:
  # By splitting testing into its own job will ensure the needs: clause for
  # static-analysis runs without waiting on the entire matrix. Jobs that run
  # against macos and windows are considerably slower
  test:
    uses: purpleclay/github/.github/workflows/go-test.yml@main
    with:
      go-version: ${{ vars.GO_VERSION }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  test-by-os:
    if: "!startsWith(github.ref, 'refs/tags/')"
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    uses: purpleclay/github/.github/workflows/go-test.yml@main
    with:
      os: ${{ matrix.os }}
      go-version: ${{ vars.GO_VERSION }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    uses: purpleclay/github/.github/workflows/golangci-lint.yml@main
    with:
      version: ${{ vars.GOLANGCI_LINT_VERSION }}
      go-version: ${{ vars.GO_VERSION }}
