name: ci
on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "*.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    # paths:
    #   - "**/*.go"
    #   - "*.go"
    #   - "go.mod"
    #   - "go.sum"

permissions:
  contents: read

# TODO: test [linux, mac]
# TODO: test-windows [windows]

jobs:
  test:
    runs-on: [ubuntu-24.04, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31

      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: purpleclay
          authToken: "${{ secrets.GH_CACHIX }}"

      - run: nix run .#test

  # lint:
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: golangci-lint
  #       uses: dagger/dagger-for-github@v7
  #       with:
  #         verb: call
  #         module: github.com/purpleclay/daggerverse/golang
  #         args: --src . lint
  #         cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
