# Copyright (c) 2023 Purple Clay
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# in the Software without restriction, including without limitation the rights
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: ci
on:
  push:
    branches:
      - main
    paths:
      # - "**/*.go"
      # - "*.go"
      # - "go.mod"
      # - "go.sum"
  pull_request:
    # paths:
    #   - "**/*.go"
    #   - "*.go"
    #   - "go.mod"
    #   - "go.sum"
jobs:
  # Separate into its own job to prevent SonarCloud from waiting for the entire
  # matrix to complete
  test-linux:
    uses: purpleclay/github/.github/workflows/go-test.yml@main
    permissions:
      contents: read
    with:
      go-version: 1.19.5
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    uses: purpleclay/github/.github/workflows/go-test.yml@main
    permissions:
      contents: read
    with:
      os: ${{ matrix.os }}
      go-version: 1.19.5
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    uses: purpleclay/github/.github/workflows/golangci-lint.yml@main
    permissions:
      contents: read
      pull-requests: read
    with:
      version: v1.51.2
      go-version: 1.19.5

  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_WORKSPACE

  static-analysis:
    uses: purpleclay/github/.github/workflows/sonarcloud.yml@sonar-workflow
    permissions:
      contents: read
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
    needs: [test-linux, lint]
