name: ci
on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "*.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    paths:
      - "**/*.go"
      - "*.go"
      - "go.mod"
      - "go.sum"

permissions:
  contents: read

jobs:
  test:
    uses: purpleclay/github/.github/workflows/go-test.yml@main
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2022]
    with:
      go-version: ${{ vars.GO_VERSION }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          module: github.com/purpleclay/daggerverse/golang
          args: --src . lint
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
