name: nsv
on:
  workflow_dispatch:

jobs:
  nsv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_NSV }}

      - name: Tag
        uses: purpleclay/nsv-action@v1
        with:
          token: ${{ secrets.GH_NSV }}
